// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecbs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ecbs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ecbs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ecbs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ecbs_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ecbs_2eproto;
namespace ECBSProto {
class ECBS;
struct ECBSDefaultTypeInternal;
extern ECBSDefaultTypeInternal _ECBS_default_instance_;
class ECBS_Location;
struct ECBS_LocationDefaultTypeInternal;
extern ECBS_LocationDefaultTypeInternal _ECBS_Location_default_instance_;
class ECBS_State;
struct ECBS_StateDefaultTypeInternal;
extern ECBS_StateDefaultTypeInternal _ECBS_State_default_instance_;
}  // namespace ECBSProto
PROTOBUF_NAMESPACE_OPEN
template<> ::ECBSProto::ECBS* Arena::CreateMaybeMessage<::ECBSProto::ECBS>(Arena*);
template<> ::ECBSProto::ECBS_Location* Arena::CreateMaybeMessage<::ECBSProto::ECBS_Location>(Arena*);
template<> ::ECBSProto::ECBS_State* Arena::CreateMaybeMessage<::ECBSProto::ECBS_State>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ECBSProto {

// ===================================================================

class ECBS_Location final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ECBSProto.ECBS.Location) */ {
 public:
  inline ECBS_Location() : ECBS_Location(nullptr) {}
  ~ECBS_Location() override;
  explicit constexpr ECBS_Location(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ECBS_Location(const ECBS_Location& from);
  ECBS_Location(ECBS_Location&& from) noexcept
    : ECBS_Location() {
    *this = ::std::move(from);
  }

  inline ECBS_Location& operator=(const ECBS_Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline ECBS_Location& operator=(ECBS_Location&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ECBS_Location& default_instance() {
    return *internal_default_instance();
  }
  static inline const ECBS_Location* internal_default_instance() {
    return reinterpret_cast<const ECBS_Location*>(
               &_ECBS_Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ECBS_Location& a, ECBS_Location& b) {
    a.Swap(&b);
  }
  inline void Swap(ECBS_Location* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ECBS_Location* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ECBS_Location* New() const final {
    return new ECBS_Location();
  }

  ECBS_Location* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ECBS_Location>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ECBS_Location& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ECBS_Location& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ECBS_Location* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ECBSProto.ECBS.Location";
  }
  protected:
  explicit ECBS_Location(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::int32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y = 2;
  void clear_y();
  ::PROTOBUF_NAMESPACE_ID::int32 y() const;
  void set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y() const;
  void _internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ECBSProto.ECBS.Location)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ecbs_2eproto;
};
// -------------------------------------------------------------------

class ECBS_State final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ECBSProto.ECBS.State) */ {
 public:
  inline ECBS_State() : ECBS_State(nullptr) {}
  ~ECBS_State() override;
  explicit constexpr ECBS_State(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ECBS_State(const ECBS_State& from);
  ECBS_State(ECBS_State&& from) noexcept
    : ECBS_State() {
    *this = ::std::move(from);
  }

  inline ECBS_State& operator=(const ECBS_State& from) {
    CopyFrom(from);
    return *this;
  }
  inline ECBS_State& operator=(ECBS_State&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ECBS_State& default_instance() {
    return *internal_default_instance();
  }
  static inline const ECBS_State* internal_default_instance() {
    return reinterpret_cast<const ECBS_State*>(
               &_ECBS_State_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ECBS_State& a, ECBS_State& b) {
    a.Swap(&b);
  }
  inline void Swap(ECBS_State* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ECBS_State* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ECBS_State* New() const final {
    return new ECBS_State();
  }

  ECBS_State* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ECBS_State>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ECBS_State& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ECBS_State& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ECBS_State* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ECBSProto.ECBS.State";
  }
  protected:
  explicit ECBS_State(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
  };
  // int32 time = 1;
  void clear_time();
  ::PROTOBUF_NAMESPACE_ID::int32 time() const;
  void set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_time() const;
  void _internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 x = 2;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::int32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y = 3;
  void clear_y();
  ::PROTOBUF_NAMESPACE_ID::int32 y() const;
  void set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y() const;
  void _internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ECBSProto.ECBS.State)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 time_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ecbs_2eproto;
};
// -------------------------------------------------------------------

class ECBS final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ECBSProto.ECBS) */ {
 public:
  inline ECBS() : ECBS(nullptr) {}
  ~ECBS() override;
  explicit constexpr ECBS(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ECBS(const ECBS& from);
  ECBS(ECBS&& from) noexcept
    : ECBS() {
    *this = ::std::move(from);
  }

  inline ECBS& operator=(const ECBS& from) {
    CopyFrom(from);
    return *this;
  }
  inline ECBS& operator=(ECBS&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ECBS& default_instance() {
    return *internal_default_instance();
  }
  static inline const ECBS* internal_default_instance() {
    return reinterpret_cast<const ECBS*>(
               &_ECBS_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ECBS& a, ECBS& b) {
    a.Swap(&b);
  }
  inline void Swap(ECBS* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ECBS* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ECBS* New() const final {
    return new ECBS();
  }

  ECBS* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ECBS>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ECBS& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ECBS& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ECBS* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ECBSProto.ECBS";
  }
  protected:
  explicit ECBS(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ECBS_Location Location;
  typedef ECBS_State State;

  // accessors -------------------------------------------------------

  enum : int {
    kObstaclesFieldNumber = 5,
    kGoalsFieldNumber = 6,
    kStartStatesFieldNumber = 7,
    kNumOfRowsFieldNumber = 1,
    kNumOfColsFieldNumber = 2,
    kWorldSizeFieldNumber = 3,
    kWorldRankFieldNumber = 4,
    kLWeightFieldNumber = 8,
  };
  // repeated .ECBSProto.ECBS.Location obstacles = 5;
  int obstacles_size() const;
  private:
  int _internal_obstacles_size() const;
  public:
  void clear_obstacles();
  ::ECBSProto::ECBS_Location* mutable_obstacles(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >*
      mutable_obstacles();
  private:
  const ::ECBSProto::ECBS_Location& _internal_obstacles(int index) const;
  ::ECBSProto::ECBS_Location* _internal_add_obstacles();
  public:
  const ::ECBSProto::ECBS_Location& obstacles(int index) const;
  ::ECBSProto::ECBS_Location* add_obstacles();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >&
      obstacles() const;

  // repeated .ECBSProto.ECBS.Location goals = 6;
  int goals_size() const;
  private:
  int _internal_goals_size() const;
  public:
  void clear_goals();
  ::ECBSProto::ECBS_Location* mutable_goals(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >*
      mutable_goals();
  private:
  const ::ECBSProto::ECBS_Location& _internal_goals(int index) const;
  ::ECBSProto::ECBS_Location* _internal_add_goals();
  public:
  const ::ECBSProto::ECBS_Location& goals(int index) const;
  ::ECBSProto::ECBS_Location* add_goals();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >&
      goals() const;

  // repeated .ECBSProto.ECBS.State start_states = 7;
  int start_states_size() const;
  private:
  int _internal_start_states_size() const;
  public:
  void clear_start_states();
  ::ECBSProto::ECBS_State* mutable_start_states(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_State >*
      mutable_start_states();
  private:
  const ::ECBSProto::ECBS_State& _internal_start_states(int index) const;
  ::ECBSProto::ECBS_State* _internal_add_start_states();
  public:
  const ::ECBSProto::ECBS_State& start_states(int index) const;
  ::ECBSProto::ECBS_State* add_start_states();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_State >&
      start_states() const;

  // int32 num_of_rows = 1;
  void clear_num_of_rows();
  ::PROTOBUF_NAMESPACE_ID::int32 num_of_rows() const;
  void set_num_of_rows(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_of_rows() const;
  void _internal_set_num_of_rows(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 num_of_cols = 2;
  void clear_num_of_cols();
  ::PROTOBUF_NAMESPACE_ID::int32 num_of_cols() const;
  void set_num_of_cols(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_of_cols() const;
  void _internal_set_num_of_cols(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 world_size = 3;
  void clear_world_size();
  ::PROTOBUF_NAMESPACE_ID::int32 world_size() const;
  void set_world_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_world_size() const;
  void _internal_set_world_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 world_rank = 4;
  void clear_world_rank();
  ::PROTOBUF_NAMESPACE_ID::int32 world_rank() const;
  void set_world_rank(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_world_rank() const;
  void _internal_set_world_rank(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float l_weight = 8;
  void clear_l_weight();
  float l_weight() const;
  void set_l_weight(float value);
  private:
  float _internal_l_weight() const;
  void _internal_set_l_weight(float value);
  public:

  // @@protoc_insertion_point(class_scope:ECBSProto.ECBS)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location > obstacles_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location > goals_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_State > start_states_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_of_rows_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_of_cols_;
  ::PROTOBUF_NAMESPACE_ID::int32 world_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 world_rank_;
  float l_weight_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ecbs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ECBS_Location

// int32 x = 1;
inline void ECBS_Location::clear_x() {
  x_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_Location::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_Location::x() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.Location.x)
  return _internal_x();
}
inline void ECBS_Location::_internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_ = value;
}
inline void ECBS_Location::set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.Location.x)
}

// int32 y = 2;
inline void ECBS_Location::clear_y() {
  y_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_Location::_internal_y() const {
  return y_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_Location::y() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.Location.y)
  return _internal_y();
}
inline void ECBS_Location::_internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_ = value;
}
inline void ECBS_Location::set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.Location.y)
}

// -------------------------------------------------------------------

// ECBS_State

// int32 time = 1;
inline void ECBS_State::clear_time() {
  time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_State::_internal_time() const {
  return time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_State::time() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.State.time)
  return _internal_time();
}
inline void ECBS_State::_internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  time_ = value;
}
inline void ECBS_State::set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.State.time)
}

// int32 x = 2;
inline void ECBS_State::clear_x() {
  x_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_State::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_State::x() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.State.x)
  return _internal_x();
}
inline void ECBS_State::_internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_ = value;
}
inline void ECBS_State::set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.State.x)
}

// int32 y = 3;
inline void ECBS_State::clear_y() {
  y_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_State::_internal_y() const {
  return y_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS_State::y() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.State.y)
  return _internal_y();
}
inline void ECBS_State::_internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_ = value;
}
inline void ECBS_State::set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.State.y)
}

// -------------------------------------------------------------------

// ECBS

// int32 num_of_rows = 1;
inline void ECBS::clear_num_of_rows() {
  num_of_rows_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::_internal_num_of_rows() const {
  return num_of_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::num_of_rows() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.num_of_rows)
  return _internal_num_of_rows();
}
inline void ECBS::_internal_set_num_of_rows(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  num_of_rows_ = value;
}
inline void ECBS::set_num_of_rows(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_of_rows(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.num_of_rows)
}

// int32 num_of_cols = 2;
inline void ECBS::clear_num_of_cols() {
  num_of_cols_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::_internal_num_of_cols() const {
  return num_of_cols_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::num_of_cols() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.num_of_cols)
  return _internal_num_of_cols();
}
inline void ECBS::_internal_set_num_of_cols(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  num_of_cols_ = value;
}
inline void ECBS::set_num_of_cols(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_of_cols(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.num_of_cols)
}

// int32 world_size = 3;
inline void ECBS::clear_world_size() {
  world_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::_internal_world_size() const {
  return world_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::world_size() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.world_size)
  return _internal_world_size();
}
inline void ECBS::_internal_set_world_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  world_size_ = value;
}
inline void ECBS::set_world_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_world_size(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.world_size)
}

// int32 world_rank = 4;
inline void ECBS::clear_world_rank() {
  world_rank_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::_internal_world_rank() const {
  return world_rank_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ECBS::world_rank() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.world_rank)
  return _internal_world_rank();
}
inline void ECBS::_internal_set_world_rank(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  world_rank_ = value;
}
inline void ECBS::set_world_rank(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_world_rank(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.world_rank)
}

// repeated .ECBSProto.ECBS.Location obstacles = 5;
inline int ECBS::_internal_obstacles_size() const {
  return obstacles_.size();
}
inline int ECBS::obstacles_size() const {
  return _internal_obstacles_size();
}
inline void ECBS::clear_obstacles() {
  obstacles_.Clear();
}
inline ::ECBSProto::ECBS_Location* ECBS::mutable_obstacles(int index) {
  // @@protoc_insertion_point(field_mutable:ECBSProto.ECBS.obstacles)
  return obstacles_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >*
ECBS::mutable_obstacles() {
  // @@protoc_insertion_point(field_mutable_list:ECBSProto.ECBS.obstacles)
  return &obstacles_;
}
inline const ::ECBSProto::ECBS_Location& ECBS::_internal_obstacles(int index) const {
  return obstacles_.Get(index);
}
inline const ::ECBSProto::ECBS_Location& ECBS::obstacles(int index) const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.obstacles)
  return _internal_obstacles(index);
}
inline ::ECBSProto::ECBS_Location* ECBS::_internal_add_obstacles() {
  return obstacles_.Add();
}
inline ::ECBSProto::ECBS_Location* ECBS::add_obstacles() {
  ::ECBSProto::ECBS_Location* _add = _internal_add_obstacles();
  // @@protoc_insertion_point(field_add:ECBSProto.ECBS.obstacles)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >&
ECBS::obstacles() const {
  // @@protoc_insertion_point(field_list:ECBSProto.ECBS.obstacles)
  return obstacles_;
}

// repeated .ECBSProto.ECBS.Location goals = 6;
inline int ECBS::_internal_goals_size() const {
  return goals_.size();
}
inline int ECBS::goals_size() const {
  return _internal_goals_size();
}
inline void ECBS::clear_goals() {
  goals_.Clear();
}
inline ::ECBSProto::ECBS_Location* ECBS::mutable_goals(int index) {
  // @@protoc_insertion_point(field_mutable:ECBSProto.ECBS.goals)
  return goals_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >*
ECBS::mutable_goals() {
  // @@protoc_insertion_point(field_mutable_list:ECBSProto.ECBS.goals)
  return &goals_;
}
inline const ::ECBSProto::ECBS_Location& ECBS::_internal_goals(int index) const {
  return goals_.Get(index);
}
inline const ::ECBSProto::ECBS_Location& ECBS::goals(int index) const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.goals)
  return _internal_goals(index);
}
inline ::ECBSProto::ECBS_Location* ECBS::_internal_add_goals() {
  return goals_.Add();
}
inline ::ECBSProto::ECBS_Location* ECBS::add_goals() {
  ::ECBSProto::ECBS_Location* _add = _internal_add_goals();
  // @@protoc_insertion_point(field_add:ECBSProto.ECBS.goals)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_Location >&
ECBS::goals() const {
  // @@protoc_insertion_point(field_list:ECBSProto.ECBS.goals)
  return goals_;
}

// repeated .ECBSProto.ECBS.State start_states = 7;
inline int ECBS::_internal_start_states_size() const {
  return start_states_.size();
}
inline int ECBS::start_states_size() const {
  return _internal_start_states_size();
}
inline void ECBS::clear_start_states() {
  start_states_.Clear();
}
inline ::ECBSProto::ECBS_State* ECBS::mutable_start_states(int index) {
  // @@protoc_insertion_point(field_mutable:ECBSProto.ECBS.start_states)
  return start_states_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_State >*
ECBS::mutable_start_states() {
  // @@protoc_insertion_point(field_mutable_list:ECBSProto.ECBS.start_states)
  return &start_states_;
}
inline const ::ECBSProto::ECBS_State& ECBS::_internal_start_states(int index) const {
  return start_states_.Get(index);
}
inline const ::ECBSProto::ECBS_State& ECBS::start_states(int index) const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.start_states)
  return _internal_start_states(index);
}
inline ::ECBSProto::ECBS_State* ECBS::_internal_add_start_states() {
  return start_states_.Add();
}
inline ::ECBSProto::ECBS_State* ECBS::add_start_states() {
  ::ECBSProto::ECBS_State* _add = _internal_add_start_states();
  // @@protoc_insertion_point(field_add:ECBSProto.ECBS.start_states)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ECBSProto::ECBS_State >&
ECBS::start_states() const {
  // @@protoc_insertion_point(field_list:ECBSProto.ECBS.start_states)
  return start_states_;
}

// float l_weight = 8;
inline void ECBS::clear_l_weight() {
  l_weight_ = 0;
}
inline float ECBS::_internal_l_weight() const {
  return l_weight_;
}
inline float ECBS::l_weight() const {
  // @@protoc_insertion_point(field_get:ECBSProto.ECBS.l_weight)
  return _internal_l_weight();
}
inline void ECBS::_internal_set_l_weight(float value) {
  
  l_weight_ = value;
}
inline void ECBS::set_l_weight(float value) {
  _internal_set_l_weight(value);
  // @@protoc_insertion_point(field_set:ECBSProto.ECBS.l_weight)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ECBSProto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ecbs_2eproto
